### ISSUE TITLE
No user watching or join stream room

### ISSUE THREAD

**Issue by bakteribaik** [Loukious/TikTokStreamKeyGenerator#1]
hi, so i just try your TiktokStreamKeyGenerator and work smooth very well, but my question is why not single person or public user join my stream room.

When I use TikTok Live Studio there are people from the public who join and comment on my stream.

**Comment by TonyUrena** [comment]
Can confirm. The user's profile broadcasts that a live event is being emitted, and the room is accesible from the profile or the share link, but it seems that it's not offered to the users swiping videos/lives.

**Comment by Loukious** [comment]
> why not single person or public user join my stream room.

I have no clue. For me no one joins the stream whether I use the TikTok Live Studio or OBS.

**Comment by marvinjoa** [comment]
I experienced the same, it seems like the stream isn't being suggested to others on the For You page when using this method.

**Comment by fooryo** [comment]
any news on this issue? @bakteribaik
