### ISSUE TITLE
Question : How to cut stream ?

### ISSUE THREAD

**Issue by HugoB07** [Loukious/TikTokStreamKeyGenerator#10]
Hello, how I can cut my stream without TikTok Live Studio software. Do you have http request or something else for end live like you go live

**Comment by Loukious** [comment]
It will end after a couple of minutes from ending the stream.

**Comment by HugoB07** [comment]
Thanks for your answer
Is not possible to do a request like TikTok Live Studio to instant cut the live ?

**Comment by Loukious** [comment]
> Thanks for your answer Is not possible to do a request like TikTok Live Studio to instant cut the live ?

It's possible. I might add it later.

**Comment by HugoB07** [comment]
ok, thanks, this could really be good

**Comment by Loukious** [comment]
> ok, thanks, this could really be good

Just released a new version with end live button. Check it out.

**Comment by HugoB07** [comment]
Thanks !!
