### ISSUE TITLE
Having an issue with running the code

### ISSUE THREAD

**Issue by FoxtrotBravo1994** [Loukious/TikTokStreamKeyGenerator#12]
Hello there, I am helping out a friend of mine running this code however when we run this program: and it would open and close if we were to run the exe file and if we were to open it in a python session it would provide a syntax error. we have also tried to run it in visual studio and it would give us an exit code of 0.

I would like to verify if we are operating on this correctly or atleast provide us a bit of a hand on what we need to provide to the python code or if we are missing out any additional program.

**Comment by Loukious** [comment]
Did you install the requirements first?
`python -m pip install -r requirements.txt`
Also a screenshot of the syntax error would help identify the issue.

**Comment by FoxtrotBravo1994** [comment]
we had tried to install the requirement but we were not sure where we suppose to place it as it said command line. was the command line suppose to be the pop up window or were we suppose to place it on a specific line in one of the lcoation

**Comment by Loukious** [comment]
> we had tried to install the requirement but we were not sure where we suppose to place it as it said command line. was the command line suppose to be the pop up window or were we suppose to place it on a specific line in one of the lcoation

Simplest way is to just use the .exe file in releases. It's probably being blocked by windows defender so temporary disable it or add the .exe file to exclusion.
