### ISSUE TITLE
Different ingest servers?

### ISSUE THREAD

**Issue by nguyenle2457** [Loukious/TikTokStreamKeyGenerator#13]
First of all, stellar work. Thank you so much for this. I can't believe it works and I hope it'll continue to (as long as TikTok allows it or provide stream keys no questions asked). 
I sifted through your code and I can see that there are two ingest servers, both located in US East.
Two concerns:
1. Do these affect regional visibility, or is that dictated by priority_region?
2. Users not within close proximity of these servers may experience routing issues and thus, dropped frames. Have these always been the only ingest servers available? Or are there more that have yet to be discovered/implemented?

**Comment by Loukious** [comment]
Thank you.
> 1. Do these affect regional visibility, or is that dictated by priority_region?
They don't affect visibility, priority_region is the only one that should affected (with no guarantee as the name suggests)
> 2. Users not within close proximity of these servers may experience routing issues and thus, dropped frames. Have these always been the only ingest servers available? Or are there more that have yet to be discovered/implemented?
As far as I know yes. I looked up TikTok hosts [here](https://gist.github.com/RupGautam/e6953b6e0a68ece63e6721309135190f) and they seem to be the only ones related the streaming. Also only one of them is supposed to work for you and it's based on the account not the location. Also routing shouldn't be an issue as DNS will auto-resolve it to the closest host.
Example: I'm in Africa and when I ping the server `webcast16-normal-c-useast1a.tiktokv.com` I get 45ms
![image](https://github.com/Loukious/TikTokStreamKeyGenerator/assets/24696530/fc60dce7-1c0c-4848-8a2f-572d6c99afe6)

**Comment by nguyenle2457** [comment]
You're very much correct. It would appear that they use anycast DNS. I didn't even think of pinging it to find out, and sure enough its only 30ms.
As for the visibility concern, I suppose that's to be expected since this is a nice enough workaround for now, until they give an option to stream using third party software using streamkey.
However, I thought of another potential issue: Do you know if this effectively bypasses the content moderation system that's seen in TikTok Live Studio? Normally, you'd get a warning for any guidelines violations from within the Live Studio. If the answer is no then is there a way to broadcast said warning(s) to us?

**Comment by Loukious** [comment]
> As for the visibility concern, I suppose that's to be expected since this is a nice enough workaround for now

It works actually the exact same way as LIVE Studio except it doesn't give you the choice (so in a sense this app is better).

> Do you know if this effectively bypasses the content moderation system that's seen in TikTok Live Studio?

No it doesn't.

> is there a way to broadcast said warning(s) to us?

Probably yes maybe I'll implement it in the future.

**Comment by nguyenle2457** [comment]
> > Do you know if this effectively bypasses the content moderation system that's seen in TikTok Live Studio?
> 
> No it doesn't.
> 
> > is there a way to broadcast said warning(s) to us?
> 
> Probably yes maybe I'll implement it in the future.
Good to know and great that you're considering this as a future feature!
