### ISSUE TITLE
Server not available 

### ISSUE THREAD

**Issue by KelboLive** [Loukious/TikTokStreamKeyGenerator#14]
When attempting to go live I'm hit with the cannot connect to server. I've tried both server options and changing my region settings to no avail.

**Comment by Loukious** [comment]
There's no way to help you without any screenshots from the app/console.

**Comment by HugoB07** [comment]
Hello same problem here
![image-2.png](https://github.com/Loukious/TikTokStreamKeyGenerator/assets/78440460/211e4029-d12f-4bdb-a773-5686e2839d96)

**Comment by Loukious** [comment]
> Hello same problem here ![image-2.png](https://private-user-images.githubusercontent.com/78440460/327398886-211e4029-d12f-4bdb-a773-5686e2839d96.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQ3MDc5NTUsIm5iZiI6MTcxNDcwNzY1NSwicGF0aCI6Ii83ODQ0MDQ2MC8zMjczOTg4ODYtMjExZTQwMjktZDEyZi00YmRiLWE3NzMtNTY4NmUyODM5ZDk2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MDMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTAzVDAzNDA1NVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQwNTg0NmJiNzU1OTcwNjU2OWI1MTJjNmU2ZDJiYzM5ZTJjYjM0YjgwMDE2NzY1ZWNkZDVkNzcwY2UzNzdjMzUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Xdh5kko35vFZsPslEcqBQo5d7KRQBRXny5D2xQ43Du8)

That's not related. It's simply telling you that you don't have Live Studio access.

**Comment by Loukious** [comment]
> ![untitled](https://private-user-images.githubusercontent.com/168463230/326552284-63ae9b27-4fbc-493e-b385-852b6793e997.JPG?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQ3MDc5NTUsIm5iZiI6MTcxNDcwNzY1NSwicGF0aCI6Ii8xNjg0NjMyMzAvMzI2NTUyMjg0LTYzYWU5YjI3LTRmYmMtNDkzZS1iMzg1LTg1MmI2NzkzZTk5Ny5KUEc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTAzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUwM1QwMzQwNTVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT00MTcwNjAxMDQ0Zjk4MGMyYzA2YmZlMzk4MGI0ODUyZDMzOWVhMWQ3MDdkYjFjNGI0OGNkMzM4ZmEyMGE2NTc0JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.Is1YHqg9XUxyex1urcFVBQOX5GHWs4yaViiFZJ-Es60)

I posted a new update. Give it a try.
