### ISSUE TITLE
Connection Error using the latest update

### ISSUE THREAD

**Issue by oriax1578** [Loukious/TikTokStreamKeyGenerator#15]
Downloaded the latest version with the updated dynamic stream url and keep getting connection errors. I tried running in admin as well to no avail. 

The exe DEV version works fine if running admin but the end stream doesnt work. Would have to close app, clear cookies, relogin then I can close it.

![Screenshot 2024-05-04 051757](https://github.com/Loukious/TikTokStreamKeyGenerator/assets/64349891/c27c8aaf-febe-4343-916e-661e47983f27)

**Comment by Loukious** [comment]
> Downloaded the latest version with the updated dynamic stream url and keep getting connection errors. I tried running in admin as well to no avail.
> 
> The exe DEV version works fine if running admin but the end stream doesnt work. Would have to close app, clear cookies, relogin then I can close it.
> 
> ![Screenshot 2024-05-04 051757](https://private-user-images.githubusercontent.com/64349891/327941169-c27c8aaf-febe-4343-916e-661e47983f27.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQ4MjU1OTcsIm5iZiI6MTcxNDgyNTI5NywicGF0aCI6Ii82NDM0OTg5MS8zMjc5NDExNjktYzI3YzhhYWYtZmViZS00MzQzLTkxNmUtNjYxZTQ3OTgzZjI3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MDQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTA0VDEyMjEzN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWEyYWE3ZDNhNzg1YmZjMTBhNmNjYzkyNGZhNzNjZDNkYTk3OWZlOTZkYmY0OTllMzA5YmVmMmFiN2Y4ZGRmMjQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.ewU7uGnQsqutJhuH5lrkm-V4A7Jd_yFhYBwY4UJnaDc)

Contact me on discord "loukios". So from my understand, it goes live just fine but can't end the stream?

**Comment by Loukious** [comment]
I changed how the url is being fetched. Try the new version.
