### ISSUE TITLE
Feature Request

### ISSUE THREAD

**Issue by oriax1578** [Loukious/TikTokStreamKeyGenerator#16]
Hi I was wondering if its possible to add a option to choose Mobile Live Stream instead of Live Studio, The reason is because Live Studio / Streamkeys usually have little to no viewers but those that stream on Mobile get alot more. Like spoofing or using mobile user agent and stream urls ect (I dont know really just guesses) That would be so awesome if possible.

**Comment by Loukious** [comment]
It's definitely possible. Might work on it in the future.

**Comment by Loukious** [comment]
> Hi I was wondering if its possible to add a option to choose Mobile Live Stream instead of Live Studio, The reason is because Live Studio / Streamkeys usually have little to no viewers but those that stream on Mobile get alot more. Like spoofing or using mobile user agent and stream urls ect (I dont know really just guesses) That would be so awesome if possible.

Feature added. You can now choose to stream as if you're using mobile camera or screensharing from mobile.
