### ISSUE TITLE
Feature Request

### ISSUE THREAD

**Issue by riggsgamers** [Loukious/TikTokStreamKeyGenerator#17]
Your application is incredible!
Quick question: how do I send a message on a live stream using code?

**Comment by Loukious** [comment]
It's possible but I'm not sure if I should add that as you can simply open the browser/phone and do it.

**Comment by riggsgamers** [comment]
Yeah because i want a chat bot for command !info and other

**Comment by Loukious** [comment]
> Yeah because i want a chat bot for command !info and other

In that case you can use https://github.com/zerodytrash/TikTok-Live-Connector

**Comment by HugoB07** [comment]
With this lib, you can't send message in the chat, you can only check if a message has been send, I think @riggsgamers want to send a message from code in the chat
