### ISSUE TITLE
disconnect and reconnect loop after 2 minutes.

### ISSUE THREAD

**Issue by conan1150** [Loukious/TikTokStreamKeyGenerator#19]
disconnect and reconnect loop after 2 minutes. 
when use key to stream on obs.

Mobile camera stream mode.

**Comment by Loukious** [comment]
> disconnect and reconnect loop after 2 minutes. when use key to stream on obs.
> 
> Mobile camera stream mode.

You sure you're on the latest version? I fixed this issue in yesterday's update.

**Comment by conan1150** [comment]
thank you for your response. I already try last version under condition we login Live studio without  Live access

**Comment by oriax1578** [comment]
the other two modes work fine, Mobile camera stream doesnt work at the moment seems like it needs more parameters or something.  Testing and trying to fix it on my end as well.

**Comment by conan1150** [comment]
> the other two modes work fine, Mobile camera stream doesnt work at the moment seems like it needs more parameters or something. Testing and trying to fix it on my end as well.

it seem there some ping to check that stream is coming from real device,

**Comment by Loukious** [comment]
I still can't reproduce this. Mine is working fine.

**Comment by oriax1578** [comment]
Mine would last 30 minutes to 1hr then live ends.

**Comment by beastfighter1** [comment]
This is also happened to me! When using the "Mobile Camera Stream" spoofing option, the stream on TikTok would disconnect after around 3-5 minutes. Switched back to "No Spoofing" and had no issues.

**Comment by oriax1578** [comment]
> This is also happened to me! When using the "Mobile Camera Stream" spoofing option, the stream on TikTok would disconnect after around 3-5 minutes. Switched back to "No Spoofing" and had no issues. Using my exported cookies from my browser as well.

The other option works think it was screen share

**Comment by Loukious** [comment]
I've just released a new update. You'll need to download another app from [here](https://github.com/Loukious/TikTokDeviceGenerator/releases/latest) and use it to generate device_id and some other stuff then copy them over to the TikTokStreamKeyGenerator. Let me know how it goes.

**Comment by mrkio9** [comment]
I have tested new application. 
It seem not working fine.
Device Generator
![image](https://github.com/Loukious/TikTokStreamKeyGenerator/assets/101476635/b1fe1f12-9c16-41ad-9347-ab9a39bfc8a8)
Tiktok Generator
![image](https://github.com/Loukious/TikTokStreamKeyGenerator/assets/101476635/2b8c9ac3-ea5b-4a3d-8c88-b22d48d14a41)
ffmpeg living 16 minutes and disconnect
![image](https://github.com/Loukious/TikTokStreamKeyGenerator/assets/101476635/014e2edb-5dbe-4df6-b062-190f6b1cf8ac)

**Comment by mrkio9** [comment]
In another application livestream, it use some more https link but i dont know "agruments" put into this https 
Maybe, it can help you
![image](https://github.com/Loukious/TikTokStreamKeyGenerator/assets/101476635/4faf4a19-2406-49b3-a1fb-e7929eeede40)

**Comment by Loukious** [comment]
I've uploaded a new version. Give it a try (if this doesn't work tbh I give up). Stream stayed up for 3 hours in my testings.

**Comment by conan1150** [comment]
> I've uploaded a new version. Give it a try (if this doesn't work tbh I give up). Stream stayed up for 3 hours in my testings.

just worked perfectly thank you so much.

**Comment by conan1150** [comment]
I have to close this issue.

**Comment by Loukious** [comment]
> > I've uploaded a new version. Give it a try (if this doesn't work tbh I give up). Stream stayed up for 3 hours in my testings.
> 
> just worked perfectly thank you so much.

Although now the stream stays live, it seems like you won't get views from recommendations. There's still some work to be done (missing header signature) but I didn't find anything open source to use.
