### ISSUE TITLE
Landscape mode disabled

### ISSUE THREAD

**Issue by vanevskidarko** [Loukious/TikTokStreamKeyGenerator#2]
I see people using this and they have altered the code I guess and have disabled landscape mkde, e.g when you try to go into landscape mode on their stream it buffers forever until it crashes tiktok, checked for both PC and Android.

Any idea how I can inplement that as well?

**Comment by Loukious** [comment]
Does this still exists?

**Comment by rvteodoro** [comment]
Before I can do that, you just need to set multi_stream_scene to true. But now its not working
