### ISSUE TITLE
Region Info Mixed Up

### ISSUE THREAD

**Issue by oriax1578** [Loukious/TikTokStreamKeyGenerator#20]
I was using fiddler and found that priority_region in tiktok live studio uses countries, but in the tiktokstreamkeygenerator the combolist shows languages instead.  for example priority_region "en" is a nogo, it should be "us" for example. 

![Screenshot 2024-05-10 150123](https://github.com/Loukious/TikTokStreamKeyGenerator/assets/64349891/1eb23384-58e2-4dc4-ba94-c90bc0087c60)

**Comment by Loukious** [comment]
Thank you for your report. This was fixed.
