### ISSUE TITLE
Account banned after using tool

### ISSUE THREAD

**Issue by beastfighter1** [Loukious/TikTokStreamKeyGenerator#23]
First of all, love the program. It worked great and was way better than using TikTok Live Studio. Unfortunately, I believe my account got banned as a result. I'm not sure what exactly set it off, perhaps it was the spoofing options. Either way, I would strongly advise warning people to use at their own risk.

**Comment by Loukious** [comment]
I doubt it would cause any ban. The only ban it may cause is shadowban when you issue too many keys in a short time period. Also TikTok would just ban/revoke your live access not just ban your account all together.
