### ISSUE TITLE
Disconnect a few minutes/hours when use Mobile Camera Stream

### ISSUE THREAD

**Issue by mrkio9** [Loukious/TikTokStreamKeyGenerator#25]
Disconnect a few minutes/hours when use Mobile Camera Stream
Use Nospoofing and Mobile Screenshare is fine. But Mobile Camera Stream Function is not working well. I think its lost some agruments to undetect by tiktok. Can u share your method to get all agruments of Mobile Camera Stream Function?

**Comment by mrkio9** [comment]
You can make a test with account > 1k followers, livestream by Mobile Camera Stream with ffmpeg and wait a few minutes or few hours (if lucky)

**Comment by Loukious** [comment]
Already has been reported in #19
