### ISSUE TITLE
proxy with streamkey

### ISSUE THREAD

**Issue by mrkio9** [Loukious/TikTokStreamKeyGenerator#28]
If I create a stream key, do I have to add a proxy to change the region to the one I want? and how? can you give me a suggest? i think if only choose region, its not fine. easy to block and havenot suggested by tiktok at region i choosed

**Comment by mrkio9** [comment]
btw, your lastest version is awesome. how do you know it too fast lol @Loukious

**Comment by Loukious** [comment]
> If I create a stream key, do I have to add a proxy to change the region to the one I want? and how? can you give me a suggest? i think if only choose region, its not fine. easy to block and havenot suggested by tiktok at region i choosed

Haven't tried it but I assume using a VPN will be just fine. Open VPN then generate the key.
