### ISSUE TITLE
Trojan:Win32/Wacatac.H!ml

### ISSUE THREAD

**Issue by manstfu** [Loukious/TikTokStreamKeyGenerator#30]
Windows detect trojan, Trojan:Win32/Wacatac.H!ml

**Comment by oriax1578** [comment]
> Windows detect trojan, Trojan:Win32/Wacatac.H!ml

False positive, all the source code is here for viewing ect.

**Comment by Loukious** [comment]
As @oriax1578 said, it's false positive (caused by pyinstaller). All the code is here and the binaries are auto generated by github actions.

**Comment by manstfu** [comment]
Yea, i think it is more caused by Selenium, a better solution would be to manually set SessionID instead of Selenium or Chrome extension

**Comment by Loukious** [comment]
> Yea, i think it is more caused by Selenium, a better solution would be to manually set SessionID instead of Selenium or Chrome extension

Nah I have a couple more projects compiled by PyInstaller and the don't have Selenium in it and they still get detected as a Trojan.

**Comment by manstfu** [comment]
I tried it and everything works like charm only problem is that Gaming category is missing 'Others games' subcategory, And i got 0 FYP exposure using Mobile Camera Stream, only followers joining..

**Comment by Loukious** [comment]
> I tried it and everything works like charm only problem is that Gaming category is missing 'Others games' subcategory, 

Didn't know about that.
> And i got 0 FYP exposure using Mobile Camera Stream, only followers joining..

Yeah spoofing has currently an issue.
