### ISSUE TITLE
Creating a live room gets no traffic

### ISSUE THREAD

**Issue by affluentmind** [Loukious/TikTokStreamKeyGenerator#32]
If i use the stream key and base url for streaming i get 0 traffic, any idea why is that? normally i get 1200 per hour but using this method gets me around 2 per hour i tried latest version and prev version same behavior,  as soon as i switch to mobile or tt live studio it works normally?

**Comment by Loukious** [comment]
Don't use spoofing it's broken.

**Comment by vtandroid** [comment]
@Loukious  I think in the query string, you missed device_id and install_id
![Screenshot 2024-06-12 111212](https://github.com/Loukious/TikTokStreamKeyGenerator/assets/12620821/de7f5910-73d6-4ee5-95b8-3c0db3305af4)
device_id and install_id are obtained the first time you install and open the app, it calls https://log.tiktokv.com/service/2/desktop/device_register/?aid=8311&channel=studio&os=Windows&os_version=10.0.19045&device_type=PC&device_platform=PC&version_code=0.58.2&pc_uuid=00000000-0000-0000-0000-309c23de0d9cmicro-star%20international%20co.,%20ltd.ms-7b33GMT+070076:89:b2:11:1b:7b&pc_serial=z9ampgvt&aid=8311&language=en&app_language=en&webcast_language=en&device_id=0&device_platform=windows&version_code=0.58.2&webcast_sdk_version=582&live_mode=6
response:
{
	"server_time": 1718162847,
	"device_id": 7379449133995099664,
	"install_id": 7379452964052961041,
	"new_user": 1,
	"device_id_str": "7379449133995099664",
	"install_id_str": "7379452964052961041"
}

**Comment by Loukious** [comment]
They are being used. Check https://github.com/Loukious/TikTokStreamKeyGenerator/blob/main/TiktokStreamKeyGenerator.py#L55
The issue is that they are missing some signatures in the header or the ones I'm currently using are incorrect.

**Comment by vtandroid** [comment]
I think they aren't being used if we don't use spoofing:
https://github.com/Loukious/TikTokStreamKeyGenerator/blob/6a6934b67e41160ccd4f902cfe06151ab3625f05/TiktokStreamKeyGenerator.py#L177

**Comment by manstfu** [comment]
Also Region seems not to replace the use of VPN

**Comment by oriax1578** [comment]
> Also Region seems not to replace the use of VPN, and somehow streaming without spoofing can't be done vertical, it uses Horizontal method, Spoofing mobile works with Vertical Method

Its not ment to replace a VPN, its to choose the correct region as its not universal. Using the second spoofing method works. Just not the camera mode. I use it all the time without errors.

**Comment by oriax1578** [comment]
> I think they aren't being used if we don't use spoofing:
> 
> https://github.com/Loukious/TikTokStreamKeyGenerator/blob/6a6934b67e41160ccd4f902cfe06151ab3625f05/TiktokStreamKeyGenerator.py#L177

This param is only used for tiktok live studio mode, not for the mobile spoofing. the code is correct.

**Comment by vtandroid** [comment]
> > I think they aren't being used if we don't use spoofing:
> > https://github.com/Loukious/TikTokStreamKeyGenerator/blob/6a6934b67e41160ccd4f902cfe06151ab3625f05/TiktokStreamKeyGenerator.py#L177
> 
> This param is only used for tiktok live studio mode, not for the mobile spoofing. the code is correct.

yes, when i captured the request from tiktok live studio, i saw it sending "create/room" with device_id and install_id, i think that is the problem causing the live stream to get 0 traffic

**Comment by manstfu** [comment]
what are you using to monitor api request from Tiktok App? I found this but i need to root phone
https://httptoolkit.com/

**Comment by ItsRiottz** [comment]
What I could notice is that when you do live using the tool it does not send notifications that you are live and when you use tiktok live studio it does arrive immediately.

**Comment by Loukious** [comment]
> What I could notice is that when you do live using the tool it does not send notifications that you are live and when you use tiktok live studio it does arrive immediately.

Don't use spoofing.

**Comment by ItsRiottz** [comment]
> > What I could notice is that when you do live using the tool it does not send notifications that you are live and when you use tiktok live studio it does arrive immediately.
> 
> Don't use spoofing.

In my case I am not using any type of spoofing and in the same way it never notifies from what I see.

**Comment by Loukious** [comment]
Tested it more than once and the streaming is being recommended correctly WITHOUT USING SPOOFING.
