### ISSUE TITLE
Can the login wait time be longer?

### ISSUE THREAD

**Issue by bakteribaik** [Loukious/TikTokStreamKeyGenerator#33]
-

**Comment by bakteribaik** [comment]
sorry about that, it just fixed by updating chorme to latest version

**Comment by bakteribaik** [comment]
can you make longer timeout for login, for account with 2FA i need more time to email login > email verification > connect to tiktok > verification tiktok code sended to email > opening email > put some code > captcha verification

**Comment by Loukious** [comment]
> can you make longer timeout for login, for account with 2FA i need more time to email login > email verification > connect to tiktok > verification tiktok code sended to email > opening email > put some code > captcha verification

You could use [this](https://chromewebstore.google.com/detail/export-cookie-json-file-f/nmckokihipjgplolmcmjakknndddifde) extension. 

From the readme:

> This error sometimes occurs when TikTok detects selenium. You can use this [extension](https://chromewebstore.google.com/detail/export-cookie-json-file-f/nmckokihipjgplolmcmjakknndddifde) to export your cookies and import them into the script.
> - Start by installing the above extension in your browser.
> - Log into TikTok in the browser (if not already logged in), then export the cookies using the extension (while being on TikTok's > website).
> - After that, place the file in the same directory as the script and rename it to cookies.json then start the app.
