### ISSUE TITLE
Error: Download and update LIVE Studio to the latest version

### ISSUE THREAD

**Issue by coiines** [Loukious/TikTokStreamKeyGenerator#36]
Tiktok Studio is the latest version, re-downloaded and re-installed just in case and still getting the error message. Logged in via Chrome Browser as well too.

![tiktok stream generator](https://github.com/Loukious/TikTokStreamKeyGenerator/assets/164867815/d4606e75-a209-4555-868d-8ac50d7148e7)

**Comment by HugoB07** [comment]
tiktok change the backend API to block this tool... a few month ago, we don't need to do signature, xgorgon etc etc, tiktok doesn't want users to stream via another software (only TikTok Live Studio)...

**Comment by Loukious** [comment]
> Tiktok Studio is the latest version, re-downloaded and re-installed just in case and still getting the error message. Logged in via Chrome Browser as well too.
> 
> ![tiktok stream generator](https://private-user-images.githubusercontent.com/164867815/341906178-d4606e75-a209-4555-868d-8ac50d7148e7.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTkwMTE4MzIsIm5iZiI6MTcxOTAxMTUzMiwicGF0aCI6Ii8xNjQ4Njc4MTUvMzQxOTA2MTc4LWQ0NjA2ZTc1LWEyMDktNDU1NS04NjhkLThhYzUwZDcxNDhlNy5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjIxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYyMVQyMzEyMTJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT04N2E0ZmFkYjg4ZjhiZTc0ZWM3M2Q0YjZjMzcxNGQ0YTgyYzhhYmU4ZjcyYmQ2NDhkNjMyZWNhN2EzNWM4Njg3JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.j6T2FDfy-TkCRpEl42fY7rVKac6U2IL4CdL3p7ttSOg)

Fixed on latest.



> tiktok change the backend API to block this tool... a few month ago, we don't need to do signature, xgorgon etc etc, tiktok doesn't want users to stream via another software (only TikTok Live Studio)...

Not really. The signatures were always required (for spoofing) I just didn't know that. For version block, they are just blocking people who still use the old version of Live Studio.

**Comment by HugoB07** [comment]
So why right now for none spoofing, the latest version without signature and gorgon doesn't work ?

**Comment by Loukious** [comment]
> So why right now for none spoofing, the latest version without signature and gorgon doesn't work ?

No spoofing never needed signature. It works just fine without it.
