### ISSUE TITLE
shadow ban 

### ISSUE THREAD

**Issue by ibrah3m** [Loukious/TikTokStreamKeyGenerator#37]
HI it seems there's shadow ban becuase the livestream not showing 0 traffic

**Comment by Loukious** [comment]
Don't use spoofing. Regular stream works fine.

**Comment by ibrah3m** [comment]
@Loukious  does the account eat shadowban becuase of that becasue I tested all of them

**Comment by Loukious** [comment]
> @Loukious does the account eat shadowban becuase of that becasue I tested all of them

No, only the non spoofing gets you traffic.

**Comment by ibrah3m** [comment]
ok cool how about the reigon option is it really working ?
and thanks as a Livestreamer this helps alot ur a legend

**Comment by ibrah3m** [comment]
it seems u do speak arabic too so thats GREAT

**Comment by Loukious** [comment]
> ok cool how about the reigon option is it really working ? and thanks as a Livestreamer this helps alot ur a legend

Doesn't seem to work at least for me. The region is based on the IP.
