### ISSUE TITLE
No Spoofing method

### ISSUE THREAD

**Issue by dhyanan73** [Loukious/TikTokStreamKeyGenerator#38]
I would like to use the "No Spoofing" method because I understand that it allows me to reach a wider audience and therefore get more viewers for the live stream (correct me if I'm wrong). But I have problems using this method while the others work well. In fact, although the output is generated without errors, the URL and stream key do not work in my streaming program (StreamYard). So I ask you: how does the "No Spoofing" method work? Do I need to open TikTok LIVE Studio first? Do I need to perform any actions in TikTok LIVE Studio?

**Comment by Loukious** [comment]
Spoofing is broken.
