### ISSUE TITLE
Tiktok end the stream automatically after 10-15 mins (mobile camera stream option)

### ISSUE THREAD

**Issue by eswalid** [Loukious/TikTokStreamKeyGenerator#45]
i tried the first time this tool today and tiktok keeps ending my stream after some minutes and gotta redo stream keys reput them in obs then start stream again but it keeps happening over and over. this wasn't happening when i streamed on tiktok live studio

**Comment by Loukious** [comment]
Don't use spoofing streams it clearly says it doesn't work.
