### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by rvteodoro** [Loukious/TikTokStreamKeyGenerator#7]
Do you have any documentation or anything? Is there anything we can add more in data or params? 

Also before live_studio and multi_stream_scene works together, Now when I try it doesnt work.

**Comment by v1sioner** [comment]
I tried tools is not working with the error "failed stream".
I've fill everything in the box.

**Comment by v1sioner** [comment]
![issue](https://github.com/Loukious/TikTokStreamKeyGenerator/assets/165459703/9c898a1c-5e28-46c0-9108-a5aef7f973eb)
could you please share how to fix this issue ?

**Comment by Loukious** [comment]
> ![issue](https://private-user-images.githubusercontent.com/165459703/324151205-9c898a1c-5e28-46c0-9108-a5aef7f973eb.JPG?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM1ODU3MTAsIm5iZiI6MTcxMzU4NTQxMCwicGF0aCI6Ii8xNjU0NTk3MDMvMzI0MTUxMjA1LTljODk4YTFjLTVlMjgtNDZjMC05MTA4LWE1YWVmN2Y5NzNlYi5KUEc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDIwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQyMFQwMzU2NTBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0zMWYwMmM0OWVkYWI1NGEwMmM3NDA2OTgyMTBkMTcwMGNhNzRkZTkxNDZkOTAwNTBiZDYxZWMyM2M1OWNkOWQ3JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.-7oRZmIdVzoj0khFPOtSDsRzG_eb0FywgJqNx38qsCY) could you please share how to fix this issue ?

Comment/uncomment the links in the code.

**Comment by sheirla** [comment]
does this have to have live studio access? because I tried going live without live studio access, the stream died after 2 minutes

**Comment by sheirla** [comment]
> > does this have to have live studio access? because I tried going live without live studio access, the stream died after 2 minutes
> 
> Yes you need live access.

thank you for reply after researching some parameters, now i can live longer than before without live studio access

**Comment by Loukious** [comment]
> > > does this have to have live studio access? because I tried going live without live studio access, the stream died after 2 minutes
> > 
> > 
> > Yes you need live access.
> 
> thank you for reply after researching some parameters, now i can live longer than before without live studio access

What have you changed if I may ask? Also do you have live access but not live studio?

**Comment by 0x890** [comment]
> ![issue](https://private-user-images.githubusercontent.com/165459703/324151205-9c898a1c-5e28-46c0-9108-a5aef7f973eb.JPG?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM2Mzc4NTAsIm5iZiI6MTcxMzYzNzU1MCwicGF0aCI6Ii8xNjU0NTk3MDMvMzI0MTUxMjA1LTljODk4YTFjLTVlMjgtNDZjMC05MTA4LWE1YWVmN2Y5NzNlYi5KUEc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDIwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQyMFQxODI1NTBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0yM2ZmOTI1MzgzOGQ0MGFjZGU5NWQwMjY5ZGEzNWNkMzk3YTQ3MzQ3YTc0ZDYxOGQ1OThiMDIzY2FhNjdhNjYzJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.HDuIcqMVLR5xN12pOlG4oCB7EJDW_-1xYrMJtSzYxTE) could you please share how to fix this issue ?

Game tag id is wrong, please refer to :  [games tag ids](https://webcast16-normal-c-useast2a.tiktokv.com/webcast/room/hashtag/list/)

**Comment by tropix2** [comment]
No work
